---
# Docker Setup Tasks
# This file handles Docker installation and configuration

- name: Download Docker GPG key
  shell: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /tmp/docker.gpg"
  become: true

- name: Add Docker GPG key
  shell: "gpg --dearmor < /tmp/docker.gpg | sudo tee /usr/share/keyrings/docker-archive-keyring.gpg > /dev/null"
  become: true

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  become: true

- name: Install Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  become: true

- name: Start and enable Docker service
  systemd:
    name: docker
    state: started
    enabled: true
  become: true

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
  become: true

- name: Download Docker Compose
  shell: "curl -fsSL https://github.com/docker/compose/releases/latest/download/docker-compose-Linux-x86_64 -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose"
  become: true 