---
# System Setup Tasks
# This file handles basic system configuration and package installation

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: Install required packages
  apt:
    name:
      - curl
      - wget
      - gnupg
      - lsb-release
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - unzip
      - git
      - vim
      - htop
      - iptables-persistent
    state: present
  become: yes 