all:
  children:
    k8s_cluster:
      children:
        master:
          hosts:
            k8s-master:
              ansible_host: 44.198.191.148
              ansible_user: ubuntu
              ansible_ssh_private_key_file: todo-app.pem
              node_role: master
        worker:
          hosts:
            k8s-worker-1:
              ansible_host: 44.195.47.190
              ansible_user: ubuntu
              ansible_ssh_private_key_file: todo-app.pem
              node_role: worker
            k8s-worker-2:
              ansible_host: 34.201.133.177
              ansible_user: ubuntu
              ansible_ssh_private_key_file: todo-app.pem
              node_role: worker
      vars:
        ansible_python_interpreter: /usr/bin/python3
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no' 