apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
  namespace: argocd
type: Opaque
data:
  username: c2FhZG9tbmlhNTA5QGdtYWlsLmNvbQo=
  token: Z2hwX3l0c1NtS05id3lTZEVrbFRyeGpmN0kwcGFrR2FiNDQyTHR0Rg== 